apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp7
  labels:
    app: sampleapp7
    kubernetes.azure.com/generator: devhub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp7
  template:
    metadata:
      labels:
        app: sampleapp7
    spec:
      containers:
        - name: sampleapp7
          image: containernik.azurecr.io/sampleapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
