apiVersion: v1
kind: Service
metadata:
  name: sampleapp7
  namespace: default
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: sampleapp7
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80